// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sentinel.Server.Data;

#nullable disable

namespace Sentinel.Server.Data.Migrations
{
    [DbContext(typeof(SentinelDbContext))]
    [Migration("20260930130033_AlertDelay")]
    partial class AlertDelay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_version");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<bool>("Is64Bit")
                        .HasColumnType("boolean")
                        .HasColumnName("is64bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("os_version");

                    b.Property<int>("ReportedConfigVersion")
                        .HasColumnType("integer")
                        .HasColumnName("reported_config_version");

                    b.Property<int>("ReportedQueueDepth")
                        .HasColumnType("integer")
                        .HasColumnName("reported_queue_depth");

                    b.Property<byte[]>("SecretEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_encrypted");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("HostId")
                        .IsUnique()
                        .HasDatabaseName("ix_agents_host_id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("RemoteIp")
                        .HasColumnType("text")
                        .HasColumnName("remote_ip");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_audit_log_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_log_tenant_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.BackupRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArtifactPath")
                        .HasColumnType("text")
                        .HasColumnName("artifact_path");

                    b.Property<Guid>("CheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_id");

                    b.Property<bool>("CloudEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("cloud_enabled");

                    b.Property<string>("CloudPath")
                        .HasColumnType("text")
                        .HasColumnName("cloud_path");

                    b.Property<bool>("CloudUploaded")
                        .HasColumnType("boolean")
                        .HasColumnName("cloud_uploaded");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Log")
                        .HasColumnType("text")
                        .HasColumnName("log");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("pk_backup_runs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_backup_runs_tenant_id");

                    b.HasIndex("CheckId", "Target", "FinishedAt")
                        .HasDatabaseName("ix_backup_runs_check_id_target_finished_at");

                    b.ToTable("backup_runs", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Check", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AlertDelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("alert_delay_minutes");

                    b.Property<int>("ConfirmCount")
                        .HasColumnType("integer")
                        .HasColumnName("confirm_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.PrimitiveCollection<List<string>>("IgnoredKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ignored_keys");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_checks");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_checks_host_id");

                    b.ToTable("checks", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.CheckResultRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("CheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_check_results");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_check_results_received_at");

                    b.HasIndex("CheckId", "Key", "At")
                        .HasDatabaseName("ix_check_results_check_id_key_at");

                    b.ToTable("check_results", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.CheckState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_id");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("LastChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_change_at");

                    b.Property<DateTimeOffset?>("LastResultAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_result_at");

                    b.Property<int>("PendingCount")
                        .HasColumnType("integer")
                        .HasColumnName("pending_count");

                    b.Property<int?>("PendingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("pending_status");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("integer")
                        .HasColumnName("previous_status");

                    b.Property<DateTimeOffset?>("ProblemSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("problem_since");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_check_states");

                    b.HasIndex("CheckId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_check_states_check_id_key");

                    b.ToTable("check_states", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.CheckTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_check_templates");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_check_templates_tenant_id");

                    b.ToTable("check_templates", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid?>("IssuedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_user_id");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_commands");

                    b.HasIndex("AgentId", "IssuedAt")
                        .HasDatabaseName("ix_commands_agent_id_issued_at");

                    b.ToTable("commands", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.EnrollmentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedByAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by_agent_id");

                    b.HasKey("Id")
                        .HasName("pk_enrollment_tokens");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_enrollment_tokens_tenant_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollment_tokens_token_hash");

                    b.ToTable("enrollment_tokens", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("integer")
                        .HasColumnName("config_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_hosts");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_hosts_site_id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_hosts_tenant_id_name");

                    b.ToTable("hosts", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<Guid?>("CheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_id");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<Guid?>("InProgressByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("in_progress_by_user_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("key");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastReminderAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reminder_at");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_count");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset?>("SnoozedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snoozed_until");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_incidents_tenant_id");

                    b.HasIndex("Status", "OpenedAt")
                        .HasDatabaseName("ix_incidents_status_opened_at");

                    b.HasIndex("HostId", "CheckId", "Key", "Status")
                        .HasDatabaseName("ix_incidents_host_id_check_id_key_status");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.IncidentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_incident_events");

                    b.HasIndex("IncidentId", "At")
                        .HasDatabaseName("ix_incident_events_incident_id_at");

                    b.ToTable("incident_events", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.MaintenanceWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_windows");

                    b.HasIndex("EndsAt")
                        .HasDatabaseName("ix_maintenance_windows_ends_at");

                    b.ToTable("maintenance_windows", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.MetricPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_metrics");

                    b.HasIndex("Time")
                        .HasDatabaseName("ix_metrics_time");

                    b.HasIndex("CheckId", "Key", "Name", "Time")
                        .HasDatabaseName("ix_metrics_check_id_key_name_time");

                    b.ToTable("metrics", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<byte[]>("SettingsEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("settings_encrypted");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notification_channels");

                    b.ToTable("notification_channels", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.NotificationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id")
                        .HasName("pk_notification_log");

                    b.HasIndex("IncidentId", "At")
                        .HasDatabaseName("ix_notification_log_incident_id_at");

                    b.ToTable("notification_log", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.NotificationOutbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_notification_outbox");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_notification_outbox_processed_at");

                    b.ToTable("notification_outbox", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.NotificationRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MinSeverity")
                        .HasColumnType("integer")
                        .HasColumnName("min_severity");

                    b.Property<bool>("NotifyOnResolve")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_resolve");

                    b.Property<int?>("QuietFromHour")
                        .HasColumnType("integer")
                        .HasColumnName("quiet_from_hour");

                    b.Property<int?>("QuietToHour")
                        .HasColumnType("integer")
                        .HasColumnName("quiet_to_hour");

                    b.Property<int>("RemindMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("remind_minutes");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_routes");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_notification_routes_channel_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_notification_routes_tenant_id");

                    b.ToTable("notification_routes", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sites_tenant_id");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("TotpEnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_enabled_at");

                    b.Property<byte[]>("TotpSecretEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("totp_secret_encrypted");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Agent", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.Host", "Host")
                        .WithOne("Agent")
                        .HasForeignKey("Sentinel.Server.Core.Entities.Agent", "HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agents_hosts_host_id");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Check", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.Host", "Host")
                        .WithMany("Checks")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checks_hosts_host_id");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.CheckState", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.Check", "Check")
                        .WithMany("States")
                        .HasForeignKey("CheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_states_checks_check_id");

                    b.Navigation("Check");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.CheckTemplate", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_check_templates_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Command", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commands_agents_agent_id");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.EnrollmentToken", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_tokens_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Host", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hosts_sites_site_id");

                    b.HasOne("Sentinel.Server.Core.Entities.Tenant", "Tenant")
                        .WithMany("Hosts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hosts_tenants_tenant_id");

                    b.Navigation("Site");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Incident", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.Host", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_hosts_host_id");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.IncidentEvent", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.Incident", null)
                        .WithMany("Events")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incident_events_incidents_incident_id");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.NotificationRoute", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.NotificationChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_routes_notification_channels_channel_id");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Site", b =>
                {
                    b.HasOne("Sentinel.Server.Core.Entities.Tenant", "Tenant")
                        .WithMany("Sites")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sites_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Check", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Host", b =>
                {
                    b.Navigation("Agent");

                    b.Navigation("Checks");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Incident", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Sentinel.Server.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Hosts");

                    b.Navigation("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
